// Dados dos verbos - separado do app para facilitar manutenção (adicionar/remover/editar verbos).
const VERBS_RAW = [
  {kanji:"話す",kana:"はなす",romaji:"hanasu",meaning:"falar",group:1,nivel:"N5",fraseFront:"友達と",fraseFrontKana:"ともだちと",fraseBack:"Falo com o amigo.",ptPresent:"falo",ptPast:"falei"},
  {kanji:"書く",kana:"かく",romaji:"kaku",meaning:"escrever",group:1,nivel:"N5",fraseFront:"手紙を",fraseFrontKana:"てがみを",fraseBack:"Escrevo uma carta.",ptPresent:"escrevo",ptPast:"escrevi"},
  {kanji:"聞く",kana:"きく",romaji:"kiku",meaning:"ouvir / perguntar",group:1,nivel:"N5",fraseFront:"音楽を",fraseFrontKana:"おんがくを",fraseBack:"Escuto música.",ptPresent:"ouço",ptPast:"ouvi"},
  {kanji:"読む",kana:"よむ",romaji:"yomu",meaning:"ler",group:1,nivel:"N5",fraseFront:"本を",fraseFrontKana:"ほんを",fraseBack:"Leio um livro.",ptPresent:"leio",ptPast:"li"},
  {kanji:"飲む",kana:"のむ",romaji:"nomu",meaning:"beber",group:1,nivel:"N5",fraseFront:"水を",fraseFrontKana:"みずを",fraseBack:"Bebo água.",ptPresent:"bebo",ptPast:"bebi"},
  {kanji:"待つ",kana:"まつ",romaji:"matsu",meaning:"esperar",group:1,nivel:"N5",fraseFront:"友達を",fraseFrontKana:"ともだちを",fraseBack:"Espero o amigo.",ptPresent:"espero",ptPast:"esperei"},
  {kanji:"立つ",kana:"たつ",romaji:"tatsu",meaning:"ficar de pé",group:1,nivel:"N5",fraseFront:"ここに",fraseFrontKana:"ここに",fraseBack:"Fico de pé aqui.",ptPresent:"fico de pé",ptPast:"fiquei de pé"},
  {kanji:"買う",kana:"かう",romaji:"kau",meaning:"comprar",group:1,nivel:"N5",fraseFront:"服を",fraseFrontKana:"ふくを",fraseBack:"Compro uma roupa.",ptPresent:"compro",ptPast:"comprei"},
  {kanji:"会う",kana:"あう",romaji:"au",meaning:"encontrar",group:1,nivel:"N5",fraseFront:"友達に",fraseFrontKana:"ともだちに",fraseBack:"Encontro o amigo.",ptPresent:"encontro",ptPast:"encontrei"},
  {kanji:"使う",kana:"つかう",romaji:"tsukau",meaning:"usar",group:1,nivel:"N5",fraseFront:"辞書を",fraseFrontKana:"じしょを",fraseBack:"Uso o dicionário.",ptPresent:"uso",ptPast:"usei"},
  {kanji:"行く",kana:"いく",romaji:"iku",meaning:"ir",group:1,nivel:"N5",fraseFront:"友達と学校に",fraseFrontKana:"ともだちとがっこうに",fraseBack:"Vou à escola com o amigo.",ptPresent:"vou",ptPast:"fui"},
  {kanji:"泳ぐ",kana:"およぐ",romaji:"oyogu",meaning:"nadar",group:1,nivel:"N5",fraseFront:"海で",fraseFrontKana:"うみで",fraseBack:"Nado no mar.",ptPresent:"nado",ptPast:"nadei"},
  {kanji:"急ぐ",kana:"いそぐ",romaji:"isogu",meaning:"apressar-se",group:1,nivel:"N4",fraseFront:"駅へ",fraseFrontKana:"えきへ",fraseBack:"Apresso-me até a estação.",ptPresent:"apresso-me",ptPast:"apressei-me"},
  {kanji:"死ぬ",kana:"しぬ",romaji:"shinu",meaning:"morrer",group:1,nivel:"N5",fraseFront:"病気で",fraseFrontKana:"びょうきで",fraseBack:"Morre de doença.",ptPresent:"morro",ptPast:"morri"},
  {kanji:"遊ぶ",kana:"あそぶ",romaji:"asobu",meaning:"brincar",group:1,nivel:"N5",fraseFront:"公園で",fraseFrontKana:"こうえんで",fraseBack:"Brinco no parque.",ptPresent:"brinco",ptPast:"brinquei"},
  {kanji:"呼ぶ",kana:"よぶ",romaji:"yobu",meaning:"chamar",group:1,nivel:"N5",fraseFront:"名前を",fraseFrontKana:"なまえを",fraseBack:"Chamo pelo nome.",ptPresent:"chamo",ptPast:"chamei"},
  {kanji:"飛ぶ",kana:"とぶ",romaji:"tobu",meaning:"voar",group:1,nivel:"N4",fraseFront:"空を",fraseFrontKana:"そらを",fraseBack:"Voa pelo céu.",ptPresent:"voo",ptPast:"voei"},
  {kanji:"座る",kana:"すわる",romaji:"suwaru",meaning:"sentar",group:1,nivel:"N5",fraseFront:"いすに",fraseFrontKana:"いすに",fraseBack:"Sento na cadeira.",ptPresent:"sento",ptPast:"sentei"},
  {kanji:"走る",kana:"はしる",romaji:"hashiru",meaning:"correr",group:1,nivel:"N5",fraseFront:"公園を",fraseFrontKana:"こうえんを",fraseBack:"Corro no parque.",ptPresent:"corro",ptPast:"corri"},
  {kanji:"帰る",kana:"かえる",romaji:"kaeru",meaning:"voltar",group:1,nivel:"N5",fraseFront:"家に",fraseFrontKana:"いえに",fraseBack:"Volto para casa.",ptPresent:"volto",ptPast:"voltei"},
  {kanji:"作る",kana:"つくる",romaji:"tsukuru",meaning:"fazer / criar",group:1,nivel:"N5",fraseFront:"料理を",fraseFrontKana:"りょうりを",fraseBack:"Faço comida.",ptPresent:"faço",ptPast:"fiz"},
  {kanji:"分かる",kana:"わかる",romaji:"wakaru",meaning:"entender",group:1,nivel:"N5",fraseFront:"意味が",fraseFrontKana:"いみが",fraseBack:"Entendo o significado.",ptPresent:"entendo",ptPast:"entendi"},
  {kanji:"売る",kana:"うる",romaji:"uru",meaning:"vender",group:1,nivel:"N5",fraseFront:"車を",fraseFrontKana:"くるまを",fraseBack:"Vendo o carro.",ptPresent:"vendo",ptPast:"vendi"},
  {kanji:"知る",kana:"しる",romaji:"shiru",meaning:"saber",group:1,nivel:"N5",fraseFront:"答えを",fraseFrontKana:"こたえを",fraseBack:"Sei a resposta.",ptPresent:"sei",ptPast:"soube"},
  {kanji:"持つ",kana:"もつ",romaji:"motsu",meaning:"segurar / ter",group:1,nivel:"N5",fraseFront:"かばんを",fraseFrontKana:"かばんを",fraseBack:"Seguro a bolsa.",ptPresent:"seguro",ptPast:"segurei"},
  {kanji:"押す",kana:"おす",romaji:"osu",meaning:"empurrar",group:1,nivel:"N5",fraseFront:"ボタンを",fraseFrontKana:"ボタンを",fraseBack:"Aperto o botão.",ptPresent:"empurro",ptPast:"empurrei"},
  {kanji:"貸す",kana:"かす",romaji:"kasu",meaning:"emprestar",group:1,nivel:"N5",fraseFront:"お金を",fraseFrontKana:"おかねを",fraseBack:"Empresto dinheiro.",ptPresent:"empresto",ptPast:"emprestei"},
  {kanji:"消す",kana:"けす",romaji:"kesu",meaning:"apagar",group:1,nivel:"N5",fraseFront:"電気を",fraseFrontKana:"でんきを",fraseBack:"Apago a luz.",ptPresent:"apago",ptPast:"apaguei"},
  {kanji:"洗う",kana:"あらう",romaji:"arau",meaning:"lavar",group:1,nivel:"N5",fraseFront:"手を",fraseFrontKana:"てを",fraseBack:"Lavo as mãos.",ptPresent:"lavo",ptPast:"lavei"},
  {kanji:"歌う",kana:"うたう",romaji:"utau",meaning:"cantar",group:1,nivel:"N5",fraseFront:"歌を",fraseFrontKana:"うたを",fraseBack:"Canto uma música.",ptPresent:"canto",ptPast:"cantei"},
  {kanji:"食べる",kana:"たべる",romaji:"taberu",meaning:"comer",group:2,nivel:"N5",fraseFront:"ご飯を",fraseFrontKana:"ごはんを",fraseBack:"Como arroz.",ptPresent:"como",ptPast:"comi"},
  {kanji:"見る",kana:"みる",romaji:"miru",meaning:"ver",group:2,nivel:"N5",fraseFront:"映画を",fraseFrontKana:"えいがを",fraseBack:"Vejo um filme.",ptPresent:"vejo",ptPast:"vi"},
  {kanji:"起きる",kana:"おきる",romaji:"okiru",meaning:"acordar",group:2,nivel:"N5",fraseFront:"朝早く",fraseFrontKana:"あさはやく",fraseBack:"Acordo cedo de manhã.",ptPresent:"acordo",ptPast:"acordei"},
  {kanji:"寝る",kana:"ねる",romaji:"neru",meaning:"dormir",group:2,nivel:"N5",fraseFront:"早く",fraseFrontKana:"はやく",fraseBack:"Durmo cedo.",ptPresent:"durmo",ptPast:"dormi"},
  {kanji:"出る",kana:"でる",romaji:"deru",meaning:"sair",group:2,nivel:"N5",fraseFront:"家を",fraseFrontKana:"いえを",fraseBack:"Saio de casa.",ptPresent:"saio",ptPast:"saí"},
  {kanji:"入れる",kana:"いれる",romaji:"ireru",meaning:"colocar dentro",group:2,nivel:"N5",fraseFront:"かばんに",fraseFrontKana:"かばんに",fraseBack:"Coloco na bolsa.",ptPresent:"coloco dentro",ptPast:"coloquei dentro"},
  {kanji:"教える",kana:"おしえる",romaji:"oshieru",meaning:"ensinar",group:2,nivel:"N5",fraseFront:"日本語を",fraseFrontKana:"にほんごを",fraseBack:"Ensino japonês.",ptPresent:"ensino",ptPast:"ensinei"},
  {kanji:"覚える",kana:"おぼえる",romaji:"oboeru",meaning:"lembrar / memorizar",group:2,nivel:"N4",fraseFront:"単語を",fraseFrontKana:"たんごを",fraseBack:"Memorizo palavras.",ptPresent:"lembro",ptPast:"lembrei"},
  {kanji:"忘れる",kana:"わすれる",romaji:"wasureru",meaning:"esquecer",group:2,nivel:"N5",fraseFront:"名前を",fraseFrontKana:"なまえを",fraseBack:"Esqueço o nome.",ptPresent:"esqueço",ptPast:"esqueci"},
  {kanji:"開ける",kana:"あける",romaji:"akeru",meaning:"abrir",group:2,nivel:"N5",fraseFront:"ドアを",fraseFrontKana:"ドアを",fraseBack:"Abro a porta.",ptPresent:"abro",ptPast:"abri"},
  {kanji:"閉める",kana:"しめる",romaji:"shimeru",meaning:"fechar",group:2,nivel:"N5",fraseFront:"窓を",fraseFrontKana:"まどを",fraseBack:"Fecho a janela.",ptPresent:"fecho",ptPast:"fechei"},
  {kanji:"借りる",kana:"かりる",romaji:"kariru",meaning:"pedir emprestado",group:2,nivel:"N5",fraseFront:"本を",fraseFrontKana:"ほんを",fraseBack:"Pego um livro emprestado.",ptPresent:"peço emprestado",ptPast:"pedi emprestado"},
  {kanji:"考える",kana:"かんがえる",romaji:"kangaeru",meaning:"pensar",group:2,nivel:"N4",fraseFront:"将来を",fraseFrontKana:"しょうらいを",fraseBack:"Penso no futuro.",ptPresent:"penso",ptPast:"pensei"},
  {kanji:"感じる",kana:"かんじる",romaji:"kanjiru",meaning:"sentir",group:2,nivel:"N3",fraseFront:"幸せを",fraseFrontKana:"しあわせを",fraseBack:"Sinto felicidade.",ptPresent:"sinto",ptPast:"senti"},
  {kanji:"決める",kana:"きめる",romaji:"kimeru",meaning:"decidir",group:2,nivel:"N4",fraseFront:"予定を",fraseFrontKana:"よていを",fraseBack:"Decido o plano.",ptPresent:"decido",ptPast:"decidi"},
  {kanji:"比べる",kana:"くらべる",romaji:"kuraberu",meaning:"comparar",group:2,nivel:"N3",fraseFront:"値段を",fraseFrontKana:"ねだんを",fraseBack:"Comparo os preços.",ptPresent:"comparo",ptPast:"comparei"},
  {kanji:"捨てる",kana:"すてる",romaji:"suteru",meaning:"jogar fora",group:2,nivel:"N4",fraseFront:"ごみを",fraseFrontKana:"ごみを",fraseBack:"Jogo o lixo fora.",ptPresent:"jogo fora",ptPast:"joguei fora"},
  {kanji:"掛ける",kana:"かける",romaji:"kakeru",meaning:"pendurar",group:2,nivel:"N4",fraseFront:"壁に",fraseFrontKana:"かべに",fraseBack:"Penduro na parede.",ptPresent:"penduro",ptPast:"pendurei"},
  {kanji:"助ける",kana:"たすける",romaji:"tasukeru",meaning:"ajudar",group:2,nivel:"N4",fraseFront:"友達を",fraseFrontKana:"ともだちを",fraseBack:"Ajudo o amigo.",ptPresent:"ajudo",ptPast:"ajudei"},
  {kanji:"続ける",kana:"つづける",romaji:"tsuzukeru",meaning:"continuar",group:2,nivel:"N4",fraseFront:"勉強を",fraseFrontKana:"べんきょうを",fraseBack:"Continuo os estudos.",ptPresent:"continuo",ptPast:"continuei"},
  {kanji:"疲れる",kana:"つかれる",romaji:"tsukareru",meaning:"cansar-se",group:2,nivel:"N4",fraseFront:"仕事で",fraseFrontKana:"しごとで",fraseBack:"Canso-me com o trabalho.",ptPresent:"canso-me",ptPast:"cansei-me"},
  {kanji:"生まれる",kana:"うまれる",romaji:"umareru",meaning:"nascer",group:2,nivel:"N4",fraseFront:"東京で",fraseFrontKana:"とうきょうで",fraseBack:"Nasço em Tóquio.",ptPresent:"nasço",ptPast:"nasci"},
  {kanji:"晴れる",kana:"はれる",romaji:"hareru",meaning:"clarear (tempo)",group:2,nivel:"N4",fraseFront:"明日",fraseFrontKana:"あした",fraseBack:"Vai clarear amanhã (o tempo).",ptPresent:"clareia",ptPast:"clareou"},
  {kanji:"分ける",kana:"わける",romaji:"wakeru",meaning:"dividir",group:2,nivel:"N3",fraseFront:"お金を",fraseFrontKana:"おかねを",fraseBack:"Divido o dinheiro.",ptPresent:"divido",ptPast:"dividi"},
  {kanji:"混ぜる",kana:"まぜる",romaji:"mazeru",meaning:"misturar",group:2,nivel:"N3",fraseFront:"材料を",fraseFrontKana:"ざいりょうを",fraseBack:"Misturo os ingredientes.",ptPresent:"misturo",ptPast:"misturei"},
  {kanji:"調べる",kana:"しらべる",romaji:"shiraberu",meaning:"pesquisar",group:2,nivel:"N4",fraseFront:"意味を",fraseFrontKana:"いみを",fraseBack:"Pesquiso o significado.",ptPresent:"pesquiso",ptPast:"pesquisei"},
  {kanji:"答える",kana:"こたえる",romaji:"kotaeru",meaning:"responder",group:2,nivel:"N4",fraseFront:"質問に",fraseFrontKana:"しつもんに",fraseBack:"Respondo à pergunta.",ptPresent:"respondo",ptPast:"respondi"},
  {kanji:"信じる",kana:"しんじる",romaji:"shinjiru",meaning:"acreditar",group:2,nivel:"N3",fraseFront:"彼を",fraseFrontKana:"かれを",fraseBack:"Acredito nele.",ptPresent:"acredito",ptPast:"acreditei"},
  {kanji:"育てる",kana:"そだてる",romaji:"sodateru",meaning:"criar / educar",group:2,nivel:"N3",fraseFront:"子供を",fraseFrontKana:"こどもを",fraseBack:"Crio uma criança.",ptPresent:"crio",ptPast:"criei"},
  {kanji:"集める",kana:"あつめる",romaji:"atsumeru",meaning:"coletar",group:2,nivel:"N4",fraseFront:"切手を",fraseFrontKana:"きってを",fraseBack:"Coleciono selos.",ptPresent:"coleto",ptPast:"coletei"},
  {kanji:"来る",kana:"くる",romaji:"kuru",meaning:"vir",group:3,nivel:"N5",fraseFront:"友達が家に",fraseFrontKana:"ともだちがいえに",fraseBack:"O amigo vem para casa.",ptPresent:"venho",ptPast:"vim"},
  {kanji:"する",kana:"する",romaji:"suru",meaning:"fazer",group:3,nivel:"N5",fraseFront:"宿題を",fraseFrontKana:"しゅくだいを",fraseBack:"Faço a lição de casa.",ptPresent:"faço",ptPast:"fiz"},
  {kanji:"勉強する",kana:"べんきょうする",romaji:"benkyou suru",meaning:"estudar",group:3,nivel:"N5",fraseFront:"図書館で",fraseFrontKana:"としょかんで",fraseBack:"Estudo na biblioteca.",ptPresent:"estudo",ptPast:"estudei"},
  {kanji:"練習する",kana:"れんしゅうする",romaji:"renshuu suru",meaning:"praticar",group:3,nivel:"N5",fraseFront:"ピアノを",fraseFrontKana:"ピアノを",fraseBack:"Pratico piano.",ptPresent:"pratico",ptPast:"pratiquei"},
  {kanji:"運動する",kana:"うんどうする",romaji:"undou suru",meaning:"exercitar-se",group:3,nivel:"N4",fraseFront:"公園で",fraseFrontKana:"こうえんで",fraseBack:"Exercito-me no parque.",ptPresent:"exercito-me",ptPast:"exercitei-me"},
  {kanji:"料理する",kana:"りょうりする",romaji:"ryouri suru",meaning:"cozinhar",group:3,nivel:"N5",fraseFront:"うちで",fraseFrontKana:"うちで",fraseBack:"Cozinho em casa.",ptPresent:"cozinho",ptPast:"cozinhei"},
  {kanji:"旅行する",kana:"りょこうする",romaji:"ryokou suru",meaning:"viajar",group:3,nivel:"N5",fraseFront:"日本を",fraseFrontKana:"にほんを",fraseBack:"Viajo pelo Japão.",ptPresent:"viajo",ptPast:"viajei"},
  {kanji:"結婚する",kana:"けっこんする",romaji:"kekkon suru",meaning:"casar",group:3,nivel:"N5",fraseFront:"来年",fraseFrontKana:"らいねん",fraseBack:"Caso no ano que vem.",ptPresent:"caso",ptPast:"casei"},
  {kanji:"卒業する",kana:"そつぎょうする",romaji:"sotsugyou suru",meaning:"formar-se",group:3,nivel:"N4",fraseFront:"大学を",fraseFrontKana:"だいがくを",fraseBack:"Formo-me na faculdade.",ptPresent:"formo-me",ptPast:"formei-me"},
  {kanji:"就職する",kana:"しゅうしょくする",romaji:"shuushoku suru",meaning:"conseguir emprego",group:3,nivel:"N3",fraseFront:"会社に",fraseFrontKana:"かいしゃに",fraseBack:"Consigo emprego na empresa.",ptPresent:"consigo emprego",ptPast:"consegui emprego"},
  {kanji:"掃除する",kana:"そうじする",romaji:"souji suru",meaning:"limpar",group:3,nivel:"N5",fraseFront:"部屋を",fraseFrontKana:"へやを",fraseBack:"Limpo o quarto.",ptPresent:"limpo",ptPast:"limpei"},
  {kanji:"洗濯する",kana:"せんたくする",romaji:"sentaku suru",meaning:"lavar roupa",group:3,nivel:"N5",fraseFront:"服を",fraseFrontKana:"ふくを",fraseBack:"Lavo as roupas.",ptPresent:"lavo roupa",ptPast:"lavei roupa"},
  {kanji:"電話する",kana:"でんわする",romaji:"denwa suru",meaning:"telefonar",group:3,nivel:"N5",fraseFront:"母に",fraseFrontKana:"ははに",fraseBack:"Telefono para a mãe.",ptPresent:"telefono",ptPast:"telefonei"},
  {kanji:"説明する",kana:"せつめいする",romaji:"setsumei suru",meaning:"explicar",group:3,nivel:"N4",fraseFront:"理由を",fraseFrontKana:"りゆうを",fraseBack:"Explico o motivo.",ptPresent:"explico",ptPast:"expliquei"},
  {kanji:"質問する",kana:"しつもんする",romaji:"shitsumon suru",meaning:"perguntar",group:3,nivel:"N4",fraseFront:"先生に",fraseFrontKana:"せんせいに",fraseBack:"Pergunto ao professor.",ptPresent:"pergunto",ptPast:"perguntei"},
  {kanji:"心配する",kana:"しんぱいする",romaji:"shinpai suru",meaning:"preocupar-se",group:3,nivel:"N4",fraseFront:"将来を",fraseFrontKana:"しょうらいを",fraseBack:"Preocupo-me com o futuro.",ptPresent:"preocupo-me",ptPast:"preocupei-me"},
  {kanji:"我慢する",kana:"がまんする",romaji:"gaman suru",meaning:"suportar / aguentar",group:3,nivel:"N3",fraseFront:"痛みを",fraseFrontKana:"いたみを",fraseBack:"Aguento a dor.",ptPresent:"aguento",ptPast:"aguentei"},
  {kanji:"準備する",kana:"じゅんびする",romaji:"junbi suru",meaning:"preparar",group:3,nivel:"N4",fraseFront:"晩ご飯を",fraseFrontKana:"ばんごはんを",fraseBack:"Preparo o jantar.",ptPresent:"preparo",ptPast:"preparei"},
  {kanji:"予約する",kana:"よやくする",romaji:"yoyaku suru",meaning:"reservar",group:3,nivel:"N4",fraseFront:"ホテルを",fraseFrontKana:"ホテルを",fraseBack:"Reservo o hotel.",ptPresent:"reservo",ptPast:"reservei"},
  {kanji:"招待する",kana:"しょうたいする",romaji:"shoutai suru",meaning:"convidar",group:3,nivel:"N4",fraseFront:"友達を",fraseFrontKana:"ともだちを",fraseBack:"Convido o amigo.",ptPresent:"convido",ptPast:"convidei"},
  {kanji:"紹介する",kana:"しょうかいする",romaji:"shoukai suru",meaning:"apresentar",group:3,nivel:"N4",fraseFront:"家族を",fraseFrontKana:"かぞくを",fraseBack:"Apresento a família.",ptPresent:"apresento",ptPast:"apresentei"},
  {kanji:"案内する",kana:"あんないする",romaji:"annai suru",meaning:"guiar",group:3,nivel:"N4",fraseFront:"道を",fraseFrontKana:"みちを",fraseBack:"Guio o caminho.",ptPresent:"guio",ptPast:"guiei"},
  {kanji:"参加する",kana:"さんかする",romaji:"sanka suru",meaning:"participar",group:3,nivel:"N3",fraseFront:"パーティーに",fraseFrontKana:"パーティーに",fraseBack:"Participo da festa.",ptPresent:"participo",ptPast:"participei"},
  {kanji:"相談する",kana:"そうだんする",romaji:"soudan suru",meaning:"consultar",group:3,nivel:"N3",fraseFront:"先生に",fraseFrontKana:"せんせいに",fraseBack:"Consulto o professor.",ptPresent:"consulto",ptPast:"consultei"},
  {kanji:"発表する",kana:"はっぴょうする",romaji:"happyou suru",meaning:"apresentar / anunciar",group:3,nivel:"N3",fraseFront:"結果を",fraseFrontKana:"けっかを",fraseBack:"Anuncio o resultado.",ptPresent:"anuncio",ptPast:"anunciei"},
  {kanji:"利用する",kana:"りようする",romaji:"riyou suru",meaning:"utilizar",group:3,nivel:"N3",fraseFront:"電車を",fraseFrontKana:"でんしゃを",fraseBack:"Utilizo o trem.",ptPresent:"utilizo",ptPast:"utilizei"},
  {kanji:"到着する",kana:"とうちゃくする",romaji:"touchaku suru",meaning:"chegar",group:3,nivel:"N4",fraseFront:"空港に",fraseFrontKana:"くうこうに",fraseBack:"Chego no aeroporto.",ptPresent:"chego",ptPast:"cheguei"},
  {kanji:"出発する",kana:"しゅっぱつする",romaji:"shuppatsu suru",meaning:"partir",group:3,nivel:"N4",fraseFront:"朝早く",fraseFrontKana:"あさはやく",fraseBack:"Parto cedo de manhã.",ptPresent:"parto",ptPast:"parti"},
  {kanji:"失敗する",kana:"しっぱいする",romaji:"shippai suru",meaning:"falhar",group:3,nivel:"N3",fraseFront:"試験に",fraseFrontKana:"しけんに",fraseBack:"Falho na prova.",ptPresent:"falho",ptPast:"falhei"},
  {kanji:"成功する",kana:"せいこうする",romaji:"seikou suru",meaning:"ter sucesso",group:3,nivel:"N3",fraseFront:"仕事で",fraseFrontKana:"しごとで",fraseBack:"Tenho sucesso no trabalho.",ptPresent:"tenho sucesso",ptPast:"tive sucesso"},
  {kanji:"言う",kana:"いう",romaji:"iu",meaning:"dizer",group:1,nivel:"N5",fraseFront:"名前を",fraseFrontKana:"なまえを",fraseBack:"Digo o nome.",ptPresent:"digo",ptPast:"disse"},
  {kanji:"歩く",kana:"あるく",romaji:"aruku",meaning:"andar / caminhar",group:1,nivel:"N5",fraseFront:"公園を",fraseFrontKana:"こうえんを",fraseBack:"Ando pelo parque.",ptPresent:"ando",ptPast:"andei"},
  {kanji:"浴びる",kana:"あびる",romaji:"abiru",meaning:"tomar banho (chuveiro)",group:2,nivel:"N5",fraseFront:"シャワーを",fraseFrontKana:"シャワーを",fraseBack:"Tomo um banho de chuveiro.",ptPresent:"tomo banho",ptPast:"tomei banho"},
  {kanji:"置く",kana:"おく",romaji:"oku",meaning:"colocar / deixar",group:1,nivel:"N5",fraseFront:"机に",fraseFrontKana:"つくえに",fraseBack:"Coloco na mesa.",ptPresent:"coloco",ptPast:"coloquei"},
  {kanji:"送る",kana:"おくる",romaji:"okuru",meaning:"enviar",group:1,nivel:"N5",fraseFront:"メールを",fraseFrontKana:"メールを",fraseBack:"Envio um e-mail.",ptPresent:"envio",ptPast:"enviei"},
  {kanji:"降りる",kana:"おりる",romaji:"oriru",meaning:"descer (de veículo)",group:2,nivel:"N5",fraseFront:"電車を",fraseFrontKana:"でんしゃを",fraseBack:"Desço do trem.",ptPresent:"desço",ptPast:"desci"},
  {kanji:"終わる",kana:"おわる",romaji:"owaru",meaning:"terminar",group:1,nivel:"N5",fraseFront:"仕事が",fraseFrontKana:"しごとが",fraseBack:"O trabalho termina.",ptPresent:"termina",ptPast:"terminou"},
  {kanji:"返す",kana:"かえす",romaji:"kaesu",meaning:"devolver",group:1,nivel:"N5",fraseFront:"本を",fraseFrontKana:"ほんを",fraseBack:"Devolvo o livro.",ptPresent:"devolvo",ptPast:"devolvi"},
  {kanji:"切る",kana:"きる",romaji:"kiru",meaning:"cortar",group:1,nivel:"N5",fraseFront:"紙を",fraseFrontKana:"かみを",fraseBack:"Corto o papel.",ptPresent:"corto",ptPast:"cortei"},
  {kanji:"着る",kana:"きる",romaji:"kiru",meaning:"vestir",group:2,nivel:"N5",fraseFront:"服を",fraseFrontKana:"ふくを",fraseBack:"Visto a roupa.",ptPresent:"visto",ptPast:"vesti"},
  {kanji:"曲がる",kana:"まがる",romaji:"magaru",meaning:"virar / dobrar",group:1,nivel:"N5",fraseFront:"右に",fraseFrontKana:"みぎに",fraseBack:"Viro à direita.",ptPresent:"viro",ptPast:"virei"},
  {kanji:"できる",kana:"できる",romaji:"dekiru",meaning:"poder / conseguir fazer",group:2,nivel:"N5",fraseFront:"日本語が",fraseFrontKana:"にほんごが",fraseBack:"Eu sei japonês (consigo japonês).",ptPresent:"consigo",ptPast:"consegui"},
  {kanji:"取る",kana:"とる",romaji:"toru",meaning:"pegar",group:1,nivel:"N5",fraseFront:"塩を",fraseFrontKana:"しおを",fraseBack:"Pego o sal.",ptPresent:"pego",ptPast:"peguei"},
  {kanji:"なる",kana:"なる",romaji:"naru",meaning:"tornar-se / ficar",group:1,nivel:"N5",fraseFront:"先生に",fraseFrontKana:"せんせいに",fraseBack:"Torno-me professor.",ptPresent:"torno-me",ptPast:"tornei-me"},
  {kanji:"習う",kana:"ならう",romaji:"narau",meaning:"aprender",group:1,nivel:"N5",fraseFront:"日本語を",fraseFrontKana:"にほんごを",fraseBack:"Aprendo japonês.",ptPresent:"aprendo",ptPast:"aprendi"},
  {kanji:"乗る",kana:"のる",romaji:"noru",meaning:"embarcar / andar de",group:1,nivel:"N5",fraseFront:"バスに",fraseFrontKana:"バスに",fraseBack:"Ando de ônibus.",ptPresent:"ando de",ptPast:"andei de"},
  {kanji:"入る",kana:"はいる",romaji:"hairu",meaning:"entrar",group:1,nivel:"N5",fraseFront:"部屋に",fraseFrontKana:"へやに",fraseBack:"Entro no quarto.",ptPresent:"entro",ptPast:"entrei"},
  {kanji:"履く",kana:"はく",romaji:"haku",meaning:"calçar",group:1,nivel:"N5",fraseFront:"靴を",fraseFrontKana:"くつを",fraseBack:"Calço o sapato.",ptPresent:"calço",ptPast:"calcei"},
  {kanji:"働く",kana:"はたらく",romaji:"hataraku",meaning:"trabalhar",group:1,nivel:"N5",fraseFront:"会社で",fraseFrontKana:"かいしゃで",fraseBack:"Trabalho na empresa.",ptPresent:"trabalho",ptPast:"trabalhei"},
  {kanji:"見せる",kana:"みせる",romaji:"miseru",meaning:"mostrar",group:2,nivel:"N5",fraseFront:"写真を",fraseFrontKana:"しゃしんを",fraseBack:"Mostro a foto.",ptPresent:"mostro",ptPast:"mostrei"},
  {kanji:"休む",kana:"やすむ",romaji:"yasumu",meaning:"descansar / faltar",group:1,nivel:"N5",fraseFront:"学校を",fraseFrontKana:"がっこうを",fraseBack:"Falto à escola.",ptPresent:"falto",ptPast:"faltei"},
  {kanji:"渡る",kana:"わたる",romaji:"wataru",meaning:"atravessar",group:1,nivel:"N5",fraseFront:"道を",fraseFrontKana:"みちを",fraseBack:"Atravesso a rua.",ptPresent:"atravesso",ptPast:"atravessei"},
  {kanji:"渡す",kana:"わたす",romaji:"watasu",meaning:"entregar",group:1,nivel:"N5",fraseFront:"鍵を",fraseFrontKana:"かぎを",fraseBack:"Entrego a chave.",ptPresent:"entrego",ptPast:"entreguei"},
  {kanji:"止まる",kana:"とまる",romaji:"tomaru",meaning:"parar",group:1,nivel:"N5",fraseFront:"電車が",fraseFrontKana:"でんしゃが",fraseBack:"O trem para.",ptPresent:"para",ptPast:"parou"},
  {kanji:"泣く",kana:"なく",romaji:"naku",meaning:"chorar",group:1,nivel:"N5",fraseFront:"映画で",fraseFrontKana:"えいがで",fraseBack:"Choro com o filme.",ptPresent:"choro",ptPast:"chorei"},
  {kanji:"脱ぐ",kana:"ぬぐ",romaji:"nugu",meaning:"tirar (roupa)",group:1,nivel:"N5",fraseFront:"靴を",fraseFrontKana:"くつを",fraseBack:"Tiro o sapato.",ptPresent:"tiro",ptPast:"tirei"},
  {kanji:"始まる",kana:"はじまる",romaji:"hajimaru",meaning:"começar",group:1,nivel:"N5",fraseFront:"映画が",fraseFrontKana:"えいがが",fraseBack:"O filme começa.",ptPresent:"começa",ptPast:"começou"},
  {kanji:"降る",kana:"ふる",romaji:"furu",meaning:"chover / nevar",group:1,nivel:"N5",fraseFront:"雨が",fraseFrontKana:"あめが",fraseBack:"Chove.",ptPresent:"chove",ptPast:"choveu"},
  {kanji:"着く",kana:"つく",romaji:"tsuku",meaning:"chegar",group:1,nivel:"N5",fraseFront:"駅に",fraseFrontKana:"えきに",fraseBack:"Chego na estação.",ptPresent:"chego",ptPast:"cheguei"},
  {kanji:"手伝う",kana:"てつだう",romaji:"tetsudau",meaning:"ajudar (numa tarefa)",group:1,nivel:"N5",fraseFront:"母を",fraseFrontKana:"ははを",fraseBack:"Ajudo a mãe.",ptPresent:"ajudo",ptPast:"ajudei"},
  {kanji:"ある",kana:"ある",romaji:"aru",meaning:"haver / existir (coisas)",group:1,nivel:"N5",fraseFront:"机の上に",fraseFrontKana:"つくえのうえに",fraseBack:"Está em cima da mesa.",ptPresent:"há",ptPast:"havia"},
  {kanji:"いる",kana:"いる",romaji:"iru",meaning:"haver / existir (seres vivos)",group:2,nivel:"N5",fraseFront:"猫が",fraseFrontKana:"ねこが",fraseBack:"Há um gato.",ptPresent:"há",ptPast:"havia"},
];
