// Dados dos adjetivos - separado do app para facilitar manutenção (adicionar/remover/editar adjetivos).
// ptPresent/ptPast (opcionais): frase em português usada no modo escrita quando
// "é X" / "era X" soaria estranho (ex: 痛い → "dói").
// type: "i" (i-adjetivo, ex: 高い) ou "na" (na-adjetivo, ex: 元気[な])
const ADJ_RAW = [
  // ===== i-adjetivos · N5 =====
  {kanji:"大きい",kana:"おおきい",romaji:"ookii",meaning:"grande",type:"i",nivel:"N5"},
  {kanji:"小さい",kana:"ちいさい",romaji:"chiisai",meaning:"pequeno",type:"i",nivel:"N5"},
  {kanji:"新しい",kana:"あたらしい",romaji:"atarashii",meaning:"novo",type:"i",nivel:"N5"},
  {kanji:"古い",kana:"ふるい",romaji:"furui",meaning:"antigo / velho",type:"i",nivel:"N5"},
  {kanji:"いい",kana:"いい",romaji:"ii",meaning:"bom",type:"i",nivel:"N5",irregular:true},
  {kanji:"悪い",kana:"わるい",romaji:"warui",meaning:"mau / ruim",type:"i",nivel:"N5"},
  {kanji:"高い",kana:"たかい",romaji:"takai",meaning:"alto / caro",type:"i",nivel:"N5"},
  {kanji:"安い",kana:"やすい",romaji:"yasui",meaning:"barato",type:"i",nivel:"N5"},
  {kanji:"低い",kana:"ひくい",romaji:"hikui",meaning:"baixo",type:"i",nivel:"N5"},
  {kanji:"長い",kana:"ながい",romaji:"nagai",meaning:"longo",type:"i",nivel:"N5"},
  {kanji:"短い",kana:"みじかい",romaji:"mijikai",meaning:"curto",type:"i",nivel:"N5"},
  {kanji:"多い",kana:"おおい",romaji:"ooi",meaning:"muito / numeroso",type:"i",nivel:"N5"},
  {kanji:"少ない",kana:"すくない",romaji:"sukunai",meaning:"pouco",type:"i",nivel:"N5"},
  {kanji:"暑い",kana:"あつい",romaji:"atsui",meaning:"quente (clima)",type:"i",nivel:"N5",ptPresent:"está quente",ptPast:"estava quente"},
  {kanji:"寒い",kana:"さむい",romaji:"samui",meaning:"frio (clima)",type:"i",nivel:"N5",ptPresent:"está frio",ptPast:"estava frio"},
  {kanji:"熱い",kana:"あつい",romaji:"atsui",meaning:"quente (objeto/líquido)",type:"i",nivel:"N5"},
  {kanji:"冷たい",kana:"つめたい",romaji:"tsumetai",meaning:"frio / gelado (objeto)",type:"i",nivel:"N5"},
  {kanji:"難しい",kana:"むずかしい",romaji:"muzukashii",meaning:"difícil",type:"i",nivel:"N5"},
  {kanji:"易しい",kana:"やさしい",romaji:"yasashii",meaning:"fácil",type:"i",nivel:"N5"},
  {kanji:"忙しい",kana:"いそがしい",romaji:"isogashii",meaning:"ocupado",type:"i",nivel:"N5",ptPresent:"está ocupado",ptPast:"estava ocupado"},
  {kanji:"楽しい",kana:"たのしい",romaji:"tanoshii",meaning:"divertido",type:"i",nivel:"N5"},
  {kanji:"嬉しい",kana:"うれしい",romaji:"ureshii",meaning:"feliz / alegre",type:"i",nivel:"N5",ptPresent:"está feliz",ptPast:"estava feliz"},
  {kanji:"悲しい",kana:"かなしい",romaji:"kanashii",meaning:"triste",type:"i",nivel:"N5",ptPresent:"está triste",ptPast:"estava triste"},
  {kanji:"面白い",kana:"おもしろい",romaji:"omoshiroi",meaning:"interessante / divertido",type:"i",nivel:"N5"},
  {kanji:"つまらない",kana:"つまらない",romaji:"tsumaranai",meaning:"entediante / sem graça",type:"i",nivel:"N5"},
  {kanji:"美しい",kana:"うつくしい",romaji:"utsukushii",meaning:"bonito / belo",type:"i",nivel:"N5"},
  {kanji:"かわいい",kana:"かわいい",romaji:"kawaii",meaning:"fofo / bonitinho",type:"i",nivel:"N5"},
  {kanji:"強い",kana:"つよい",romaji:"tsuyoi",meaning:"forte",type:"i",nivel:"N5"},
  {kanji:"弱い",kana:"よわい",romaji:"yowai",meaning:"fraco",type:"i",nivel:"N5"},
  {kanji:"速い",kana:"はやい",romaji:"hayai",meaning:"rápido",type:"i",nivel:"N5"},
  {kanji:"遅い",kana:"おそい",romaji:"osoi",meaning:"lento / atrasado",type:"i",nivel:"N5"},
  {kanji:"近い",kana:"ちかい",romaji:"chikai",meaning:"próximo",type:"i",nivel:"N5"},
  {kanji:"遠い",kana:"とおい",romaji:"tooi",meaning:"distante / longe",type:"i",nivel:"N5"},
  {kanji:"重い",kana:"おもい",romaji:"omoi",meaning:"pesado",type:"i",nivel:"N5"},
  {kanji:"軽い",kana:"かるい",romaji:"karui",meaning:"leve",type:"i",nivel:"N5"},
  {kanji:"明るい",kana:"あかるい",romaji:"akarui",meaning:"claro / iluminado",type:"i",nivel:"N5"},
  {kanji:"暗い",kana:"くらい",romaji:"kurai",meaning:"escuro",type:"i",nivel:"N5"},
  {kanji:"広い",kana:"ひろい",romaji:"hiroi",meaning:"amplo / espaçoso",type:"i",nivel:"N5"},
  {kanji:"狭い",kana:"せまい",romaji:"semai",meaning:"estreito / apertado",type:"i",nivel:"N5"},
  {kanji:"甘い",kana:"あまい",romaji:"amai",meaning:"doce",type:"i",nivel:"N5"},
  {kanji:"辛い",kana:"からい",romaji:"karai",meaning:"picante",type:"i",nivel:"N5"},
  {kanji:"おいしい",kana:"おいしい",romaji:"oishii",meaning:"gostoso / delicioso",type:"i",nivel:"N5"},
  {kanji:"若い",kana:"わかい",romaji:"wakai",meaning:"jovem",type:"i",nivel:"N5"},
  {kanji:"眠い",kana:"ねむい",romaji:"nemui",meaning:"sonolento",type:"i",nivel:"N5",ptPresent:"está com sono",ptPast:"estava com sono"},
  {kanji:"危ない",kana:"あぶない",romaji:"abunai",meaning:"perigoso",type:"i",nivel:"N5"},

  // ===== i-adjetivos · N4 =====
  {kanji:"太い",kana:"ふとい",romaji:"futoi",meaning:"grosso",type:"i",nivel:"N4"},
  {kanji:"細い",kana:"ほそい",romaji:"hosoi",meaning:"fino / magro",type:"i",nivel:"N4"},
  {kanji:"苦い",kana:"にがい",romaji:"nigai",meaning:"amargo",type:"i",nivel:"N4"},
  {kanji:"痛い",kana:"いたい",romaji:"itai",meaning:"dolorido / dói",type:"i",nivel:"N4",ptPresent:"dói",ptPast:"doía"},
  {kanji:"深い",kana:"ふかい",romaji:"fukai",meaning:"profundo",type:"i",nivel:"N4"},
  {kanji:"浅い",kana:"あさい",romaji:"asai",meaning:"raso / superficial",type:"i",nivel:"N4"},
  {kanji:"丸い",kana:"まるい",romaji:"marui",meaning:"redondo",type:"i",nivel:"N4"},
  {kanji:"柔らかい",kana:"やわらかい",romaji:"yawarakai",meaning:"mole / suave",type:"i",nivel:"N4"},
  {kanji:"硬い",kana:"かたい",romaji:"katai",meaning:"duro / rígido",type:"i",nivel:"N4"},
  {kanji:"優しい",kana:"やさしい",romaji:"yasashii",meaning:"gentil / bondoso",type:"i",nivel:"N4"},
  {kanji:"怖い",kana:"こわい",romaji:"kowai",meaning:"assustador / com medo",type:"i",nivel:"N4"},
  {kanji:"恥ずかしい",kana:"はずかしい",romaji:"hazukashii",meaning:"vergonhoso",type:"i",nivel:"N4"},
  {kanji:"眩しい",kana:"まぶしい",romaji:"mabushii",meaning:"brilhante (que cega)",type:"i",nivel:"N4"},
  {kanji:"詳しい",kana:"くわしい",romaji:"kuwashii",meaning:"detalhado / versado",type:"i",nivel:"N4"},
  {kanji:"苦しい",kana:"くるしい",romaji:"kurushii",meaning:"sofrido / difícil de suportar",type:"i",nivel:"N4"},

  // ===== na-adjetivos · N5 =====
  {kanji:"元気",kana:"げんき",romaji:"genki",meaning:"bem-disposto / saudável",type:"na",nivel:"N5",ptPresent:"está bem",ptPast:"estava bem"},
  {kanji:"有名",kana:"ゆうめい",romaji:"yuumei",meaning:"famoso",type:"na",nivel:"N5"},
  {kanji:"親切",kana:"しんせつ",romaji:"shinsetsu",meaning:"gentil / atencioso",type:"na",nivel:"N5"},
  {kanji:"簡単",kana:"かんたん",romaji:"kantan",meaning:"simples / fácil",type:"na",nivel:"N5"},
  {kanji:"大変",kana:"たいへん",romaji:"taihen",meaning:"difícil / sério / demais",type:"na",nivel:"N5",ptPresent:"é difícil",ptPast:"foi difícil"},
  {kanji:"大切",kana:"たいせつ",romaji:"taisetsu",meaning:"importante / precioso",type:"na",nivel:"N5"},
  {kanji:"便利",kana:"べんり",romaji:"benri",meaning:"conveniente / útil",type:"na",nivel:"N5"},
  {kanji:"不便",kana:"ふべん",romaji:"fuben",meaning:"inconveniente",type:"na",nivel:"N5"},
  {kanji:"上手",kana:"じょうず",romaji:"jouzu",meaning:"habilidoso / bom em",type:"na",nivel:"N5",ptPresent:"é bom em",ptPast:"era bom em"},
  {kanji:"下手",kana:"へた",romaji:"heta",meaning:"sem jeito / ruim em",type:"na",nivel:"N5",ptPresent:"é ruim em",ptPast:"era ruim em"},
  {kanji:"好き",kana:"すき",romaji:"suki",meaning:"gostar (de)",type:"na",nivel:"N5",ptPresent:"gosta (de)",ptPast:"gostava (de)"},
  {kanji:"嫌い",kana:"きらい",romaji:"kirai",meaning:"não gostar / detestar",type:"na",nivel:"N5",ptPresent:"detesta",ptPast:"detestava"},
  {kanji:"暇",kana:"ひま",romaji:"hima",meaning:"livre / desocupado",type:"na",nivel:"N5",ptPresent:"está livre",ptPast:"estava livre"},
  {kanji:"静か",kana:"しずか",romaji:"shizuka",meaning:"silencioso / calmo",type:"na",nivel:"N5"},
  {kanji:"綺麗",kana:"きれい",romaji:"kirei",meaning:"bonito / limpo",type:"na",nivel:"N5"},
  {kanji:"同じ",kana:"おなじ",romaji:"onaji",meaning:"igual / mesmo",type:"na",nivel:"N5"},

  // ===== na-adjetivos · N4 =====
  {kanji:"大事",kana:"だいじ",romaji:"daiji",meaning:"importante",type:"na",nivel:"N4"},
  {kanji:"特別",kana:"とくべつ",romaji:"tokubetsu",meaning:"especial",type:"na",nivel:"N4"},
  {kanji:"必要",kana:"ひつよう",romaji:"hitsuyou",meaning:"necessário",type:"na",nivel:"N4"},
  {kanji:"十分",kana:"じゅうぶん",romaji:"juubun",meaning:"suficiente",type:"na",nivel:"N4"},
  {kanji:"立派",kana:"りっぱ",romaji:"rippa",meaning:"admirável / esplêndido",type:"na",nivel:"N4"},
  {kanji:"真剣",kana:"しんけん",romaji:"shinken",meaning:"sério / a sério",type:"na",nivel:"N4"},
  {kanji:"複雑",kana:"ふくざつ",romaji:"fukuzatsu",meaning:"complexo",type:"na",nivel:"N4"},
  {kanji:"単純",kana:"たんじゅん",romaji:"tanjun",meaning:"simples / ingênuo",type:"na",nivel:"N4"},
  {kanji:"普通",kana:"ふつう",romaji:"futsuu",meaning:"normal / comum",type:"na",nivel:"N4"},
  {kanji:"変",kana:"へん",romaji:"hen",meaning:"estranho",type:"na",nivel:"N4"},
  {kanji:"残念",kana:"ざんねん",romaji:"zannen",meaning:"lamentável / que pena",type:"na",nivel:"N4",ptPresent:"é uma pena",ptPast:"foi uma pena"},
  {kanji:"安全",kana:"あんぜん",romaji:"anzen",meaning:"seguro",type:"na",nivel:"N4"},
  {kanji:"危険",kana:"きけん",romaji:"kiken",meaning:"perigoso",type:"na",nivel:"N4"},
  {kanji:"自由",kana:"じゆう",romaji:"jiyuu",meaning:"livre",type:"na",nivel:"N4"},
  {kanji:"賑やか",kana:"にぎやか",romaji:"nigiyaka",meaning:"animado / movimentado",type:"na",nivel:"N4"},
];
